version: "2.2"
services:
  dms:
    build: ./dms
    tty: true
    stdin_open: true
    depends_on:
      - db
    expose:
      - "8080"
    restart: always
    env_file:
      - ./settings.env
    volumes:
      - ${FILEAGO_BASE}/dms/data:/dms/priv/data
      - ${FILEAGO_BASE}/dms/dblogs:/dms/priv/dblogs
      - ${FILEAGO_BASE}/dms/mnesia:/dms/priv/mnesia
      - ${FILEAGO_BASE}/dms/avatars:/dms/priv/web/images/avatars
      - ${FILEAGO_BASE}/dms/fonts:/tmp/fonts
  db:
    image: graphfoundation/ongdb:3.5.1
    expose:
      - "7474"
      - "7687"
    restart: always
    env_file:
      - ./db_settings.env
    volumes:
      - ${FILEAGO_BASE}/neo4j/data:/data
  nginx:
    build: ./nginx
    ports:
      - "443:443"   # FileAgo Web Portal
#      - "5555:5555" # FileAgo Backup Service (Disabled by default. Enable only if necessary.)
    expose:
      - "9999"
    depends_on:
      - dms
    restart: always
    env_file:
      - ./settings.env
    volumes:
      - ${FILEAGO_BASE}/nginx:/tmp/certs
  lool:
    build: ./lool
    expose:
      - "9980"
    depends_on:
      - dms
    restart: always
    cap_add:
      - MKNOD
