version: "2.2"
services:
  dms:
    build: ./dms
    tty: true
    stdin_open: true
    depends_on:
      - db
    expose:
      - "8080"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    env_file:
      - ./settings.env
    volumes:
      - ${FILEAGO_BASE}/dms/data:/dms/priv/data
      - ${FILEAGO_BASE}/dms/dblogs:/dms/priv/dblogs
      - ${FILEAGO_BASE}/dms/mnesia:/dms/priv/mnesia
      - ${FILEAGO_BASE}/dms/avatars:/dms/priv/web/images/avatars
  db:
    image: vimal7370/ongdb:3.6
    expose:
      - "7474"
      - "7687"
    restart: unless-stopped
    env_file:
      - ./db_settings.env
    volumes:
      - ${FILEAGO_BASE}/neo4j/data:/data
      - ${FILEAGO_BASE}/neo4j/backup:/backup
  nginx:
    build: ./nginx
    ports:
      - "443:443"   # FileAgo Web Portal
    expose:
      - "9999"
    depends_on:
      - dms
    restart: unless-stopped
    env_file:
      - ./settings.env
    volumes:
      - ${FILEAGO_BASE}/nginx:/tmp/certs
      - ${FILEAGO_BASE}/nginx_logs:/usr/local/openresty/nginx/logs
  lool:
    build: ./lool
    expose:
      - "9980"
    depends_on:
      - dms
    restart: unless-stopped
    cap_add:
      - MKNOD
