version: '2.2'

services:
  sso:
    restart: unless-stopped
    image: 'fileago/sso:latest'
    volumes:
      - ${FILEAGO_BASE}/sso:/app/sso
    expose:
      - "8081"
    working_dir: /app
    command: "app.js"
